from vocode.streaming.models.audio import AudioEncoding

DEFAULT_OUTGOING_SAMPLING_RATE = 24000
DEFAULT_INCOMING_SAMPLING_RATE = 44100
DEFAULT_CHUNK_SIZE = 480
AUDIO_ENCODING = AudioEncoding.LINEAR16
